// Code generated by codegen; DO NOT EDIT.

package iam

import (
	"github.com/cloudquery/cloudquery/plugins/source/aws/client"
	"github.com/cloudquery/plugin-sdk/schema"
)

func UserServicesLastAccessedEntities() *schema.Table {
	return &schema.Table{
		Name:        "aws_iam_user_services_last_accessed_entities",
		Description: `https://docs.aws.amazon.com/IAM/latest/APIReference/API_ServiceLastAccessed.html`,
		Resolver:    fetchIamUserServicesLastAccessedEntities,
		Multiplex:   client.AccountMultiplex,
		Columns: []schema.Column{
			{
				Name:     "entity_details_list",
				Type:     schema.TypeJSON,
				Resolver: schema.PathResolver("EntityDetailsList"),
			},
			{
				Name:     "job_completion_date",
				Type:     schema.TypeTimestamp,
				Resolver: schema.PathResolver("JobCompletionDate"),
			},
			{
				Name:     "job_creation_date",
				Type:     schema.TypeTimestamp,
				Resolver: schema.PathResolver("JobCreationDate"),
			},
			{
				Name:     "job_status",
				Type:     schema.TypeString,
				Resolver: schema.PathResolver("JobStatus"),
			},
			{
				Name:     "error",
				Type:     schema.TypeJSON,
				Resolver: schema.PathResolver("Error"),
			},
			{
				Name:     "is_truncated",
				Type:     schema.TypeBool,
				Resolver: schema.PathResolver("IsTruncated"),
			},
			{
				Name:     "result_metadata",
				Type:     schema.TypeJSON,
				Resolver: schema.PathResolver("ResultMetadata"),
			},
		},
	}
}
