// Code generated by codegen; DO NOT EDIT directly.

package plugin

import (
	"github.com/cloudquery/plugin-sdk/schema"
	"github.com/cloudquery/plugins/source/gcp/resources/services/account"
)

func PluginAutoGeneratedTables() []*schema.Table {
	return []*schema.Table{}
}
